
name: Generate Snake Animation

on:
  schedule: # Atualiza uma vez por dia
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Marquesleticia
          outputs: dist/snake.svg
          snake_color: "#b57edc"
          snake_head_color: "#ffffff"
          background: "#0d1117"

      - name: Enviar para o branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
